cc_test(
    name = 'solution_test',
    srcs = 'solution_test.cpp',
    deps = ['//toft/system/time:time',
            '//thirdparty/glog:glog',
            '//thirdparty/perftools:tcmalloc_and_profiler',
           ]  
)

